on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing of Python Server Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run pytest with coverage
        working-directory: ./ChessLite/server/
        run: pytest --cov --cov-report=xml 

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: bharath-temp/ChessLite

  lint:
    name: Linting of Python Server Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pycodestyle
      - name: Run pycodestyle
        working-directory: ./ChessLite/server/
        run: pycodestyle .


